<?php

namespace Plugin\MyFukuoka\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MyFukuokaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyFukuokaRepository extends EntityRepository
{
}
